// ------ Search Parameters ------//
let selectedTimestamp = now(); // optionally, replace 'now()' with specific timestamp. eg 'datetime('2026-04-10T00:00:00.000Z')'
let lookBack = 3h;       // Update with how far back to look. eg '3m'(3mins), '3h'(3hrs), '3d'(3days)
let lookForward = 3h;     // Only need to update if you replace the selectTimestamp above with a datetime()
let UserEmailAddress = "";         // add if known e.g., 'john.smith@cer.gov.au'
let SourceIPs = dynamic([""]);         // add if known
let DestinationIPs = dynamic([""]);     // add multiple IPs if known, e.g., dynamic(["1.1.1.1","8.8.8.8"])
let DestinationURLs = dynamic([""]); // add multiple if known
let FileHash = dynamic([""]);
//------ Search DeviceNetworkLogs ------//
let DeviceNetworkLogs =
DeviceNetworkEvents
| where TimeGenerated between ((selectedTimestamp - lookBack) .. (selectedTimestamp + lookForward))
| where (isempty(UserEmailAddress) or tolower(InitiatingProcessAccountUpn) == tolower(UserEmailAddress))
| where (isempty(SourceIPs) or LocalIP has_any (SourceIPs))
| where (isempty(DestinationIPs) or RemoteIP has_any (DestinationIPs)) 
| extend LowerRemoteUrl = tolower(tostring(RemoteUrl))
| where (isnull(DestinationURLs) or array_length(DestinationURLs) == 0 or LowerRemoteUrl has_any (DestinationURLs))
| extend
    UserEmailAddress  = tolower(InitiatingProcessAccountUpn),
    OnPremCERId       = InitiatingProcessAccountName,
    UsersDeviceName   = DeviceName,
    SourceIP          = LocalIP,
    SourcePort        = LocalPort,
    DestinationIP     = RemoteIP,
    DestinationPort   = RemotePort,
    DestinationURL    = RemoteUrl
;
//------ Search Palo Alto Network Logs ------//
let PaloNetworkLogs =
CommonSecurityLog
| where TimeGenerated between ((selectedTimestamp - lookBack) .. (selectedTimestamp + lookForward))
| where (isempty(UserEmailAddress) or tolower(SourceUserName) == tolower(UserEmailAddress))
| extend Url_s          = tostring(RequestURL)
| where (isempty(SourceIPs) or SourceIP has_any (SourceIPs))
| where (isempty(DestinationIPs) or DestinationIP has_any (DestinationIPs))
| where (isnull(DestinationURLs) or array_length(DestinationURLs) == 0 or Url_s has_any (DestinationURLs))
| extend
    UserEmailAddress  = SourceUserName,
    DestinationIP     = DestinationIP,
    DestinationURL    = RequestURL,
    ActionType        = Activity,
    PaloSecurityRule  = DeviceCustomString1,
    URLCategory       = DeviceCustomString2,
    TrafficDirection  = FlexString2
;
//------ Search DeviceFileEvents ------//    
let FileEvents = DeviceFileEvents
| where TimeGenerated between ((selectedTimestamp - lookBack) .. (selectedTimestamp + lookForward))
| extend LowerFileHashSHA265 = tolower(tostring(SHA256)),
         LowerInitiatingFileHashSHA265 = tolower(tostring(InitiatingProcessSHA256))
| where (isnull(FileHash) or array_length(FileHash) == 0 
          or LowerFileHashSHA265 has_any (FileHash) 
          or LowerInitiatingFileHashSHA265 has_any (FileHash))
// | where ActionType == "FileCreated"
// | parse FileOriginUrl with * "://" RequestURL
;
union 
//DeviceNetworkLogs, 
PaloNetworkLogs
// , FileEvents
// | project-reorder TimeGenerated, Type, DestinationURL, DestinationIP, DestinationPort,  PaloSecurityRule, URLCategory, TrafficDirection, UserEmailAddress, UsersDeviceName, SourceIP, SourcePort
| sort by TimeGenerated asc
| take 10
